// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_OK   ResponseCode = 0
	ResponseCode_FAIL ResponseCode = 1
)

var ResponseCode_name = map[int32]string{
	0: "OK",
	1: "FAIL",
}

var ResponseCode_value = map[string]int32{
	"OK":   0,
	"FAIL": 1,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}

func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

type OrderType int32

const (
	OrderType_ASC  OrderType = 0
	OrderType_DESC OrderType = 1
)

var OrderType_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var OrderType_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

type OrderSpecification int32

const (
	OrderSpecification_PRICE              OrderSpecification = 0
	OrderSpecification_LAST_PRICE_UPDATE  OrderSpecification = 1
	OrderSpecification_PRICE_UPDATE_COUNT OrderSpecification = 2
)

var OrderSpecification_name = map[int32]string{
	0: "PRICE",
	1: "LAST_PRICE_UPDATE",
	2: "PRICE_UPDATE_COUNT",
}

var OrderSpecification_value = map[string]int32{
	"PRICE":              0,
	"LAST_PRICE_UPDATE":  1,
	"PRICE_UPDATE_COUNT": 2,
}

func (x OrderSpecification) String() string {
	return proto.EnumName(OrderSpecification_name, int32(x))
}

func (OrderSpecification) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

type FetchRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type FetchResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=api.ResponseCode" json:"code,omitempty"`
	StatusMessage        string       `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

func (m *FetchResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_OK
}

func (m *FetchResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type Order struct {
	Type                 OrderType          `protobuf:"varint,1,opt,name=type,proto3,enum=api.OrderType" json:"type,omitempty"`
	Specification        OrderSpecification `protobuf:"varint,2,opt,name=specification,proto3,enum=api.OrderSpecification" json:"specification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_ASC
}

func (m *Order) GetSpecification() OrderSpecification {
	if m != nil {
		return m.Specification
	}
	return OrderSpecification_PRICE
}

type Paging struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Paging) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListRequest struct {
	Order                OrderType `protobuf:"varint,1,opt,name=order,proto3,enum=api.OrderType" json:"order,omitempty"`
	Paging               *Paging   `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOrder() OrderType {
	if m != nil {
		return m.Order
	}
	return OrderType_ASC
}

func (m *ListRequest) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type Product struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64                `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	PriceUpdateCount     int64                `protobuf:"varint,3,opt,name=price_update_count,json=priceUpdateCount,proto3" json:"price_update_count,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{5}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPriceUpdateCount() int64 {
	if m != nil {
		return m.PriceUpdateCount
	}
	return 0
}

func (m *Product) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type ListResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=api.ResponseCode" json:"code,omitempty"`
	Page                 int64        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PagesCount           int64        `protobuf:"varint,3,opt,name=pages_count,json=pagesCount,proto3" json:"pages_count,omitempty"`
	Products             []*Product   `protobuf:"bytes,4,rep,name=Products,proto3" json:"Products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{6}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_OK
}

func (m *ListResponse) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListResponse) GetPagesCount() int64 {
	if m != nil {
		return m.PagesCount
	}
	return 0
}

func (m *ListResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.ResponseCode", ResponseCode_name, ResponseCode_value)
	proto.RegisterEnum("api.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("api.OrderSpecification", OrderSpecification_name, OrderSpecification_value)
	proto.RegisterType((*FetchRequest)(nil), "api.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "api.FetchResponse")
	proto.RegisterType((*Order)(nil), "api.Order")
	proto.RegisterType((*Paging)(nil), "api.Paging")
	proto.RegisterType((*ListRequest)(nil), "api.ListRequest")
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*ListResponse)(nil), "api.ListResponse")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x8d, 0xb1, 0x21, 0x30, 0x06, 0x64, 0x46, 0xdf, 0xd7, 0x22, 0x2a, 0x35, 0xc8, 0x6d, 0x24,
	0x84, 0x5a, 0xa7, 0xa2, 0xa7, 0x1e, 0x72, 0x40, 0x0e, 0x91, 0x50, 0x69, 0x40, 0x06, 0xa4, 0x5e,
	0x2a, 0xcb, 0xb1, 0x37, 0xd4, 0x15, 0xd8, 0x5b, 0xef, 0xfa, 0x90, 0xfc, 0x8e, 0xfe, 0x80, 0xfe,
	0xd4, 0xca, 0xb3, 0x38, 0x75, 0x54, 0xf5, 0xd0, 0x93, 0xc7, 0xef, 0x3d, 0xcd, 0xbc, 0x7d, 0x3b,
	0x0b, 0x5d, 0x9e, 0xa5, 0x51, 0x1e, 0x4a, 0xe1, 0xf0, 0x2c, 0x95, 0x29, 0xea, 0x01, 0x8f, 0x07,
	0x67, 0xbb, 0x34, 0xdd, 0xed, 0xd9, 0x05, 0x41, 0xb7, 0xf9, 0xdd, 0x85, 0x8c, 0x0f, 0x4c, 0xc8,
	0xe0, 0xc0, 0x95, 0xca, 0x1e, 0x42, 0xfb, 0x9a, 0xc9, 0xf0, 0xab, 0xc7, 0xbe, 0xe7, 0x4c, 0x48,
	0xb4, 0x40, 0xcf, 0xb3, 0x7d, 0x5f, 0x1b, 0x6a, 0xa3, 0x96, 0x57, 0x94, 0xf6, 0x17, 0xe8, 0x1c,
	0x15, 0x82, 0xa7, 0x89, 0x60, 0x78, 0x0e, 0x46, 0x98, 0x46, 0x8c, 0x34, 0xdd, 0x49, 0xcf, 0x09,
	0x78, 0xec, 0x94, 0xa4, 0x9b, 0x46, 0xcc, 0x23, 0x1a, 0xcf, 0xa1, 0x2b, 0x64, 0x20, 0x73, 0xe1,
	0x1f, 0x98, 0x10, 0xc1, 0x8e, 0xf5, 0x6b, 0xd4, 0xb4, 0xa3, 0xd0, 0x4f, 0x0a, 0xb4, 0xbf, 0x41,
	0x7d, 0x99, 0x45, 0x2c, 0x43, 0x1b, 0x0c, 0x79, 0xcf, 0xcb, 0xb6, 0x5d, 0x6a, 0x4b, 0xcc, 0xe6,
	0x9e, 0x33, 0x8f, 0x38, 0xbc, 0x84, 0x8e, 0xe0, 0x2c, 0x8c, 0xef, 0xe2, 0x30, 0x90, 0x71, 0x9a,
	0x50, 0xcb, 0xee, 0xe4, 0xf9, 0x6f, 0xf1, 0xba, 0x4a, 0x7b, 0x4f, 0xd5, 0xf6, 0x07, 0x68, 0xac,
	0x82, 0x5d, 0x9c, 0xec, 0x10, 0xc1, 0xe0, 0x85, 0xa5, 0x62, 0x98, 0xee, 0x51, 0x8d, 0x2f, 0xa0,
	0x55, 0x7c, 0x7d, 0x11, 0x3f, 0x28, 0xaf, 0xba, 0xd7, 0x2c, 0x80, 0x75, 0xfc, 0xc0, 0xec, 0xcf,
	0x60, 0x2e, 0x62, 0x21, 0xcb, 0x98, 0x5e, 0x43, 0x3d, 0x2d, 0xc6, 0xfd, 0xc5, 0xad, 0x22, 0xf1,
	0x15, 0x34, 0x38, 0xcd, 0xa3, 0x76, 0xe6, 0xc4, 0x24, 0x99, 0xb2, 0xe0, 0x1d, 0x29, 0xfb, 0xa7,
	0x06, 0xa7, 0x2b, 0x75, 0x75, 0x85, 0xad, 0x24, 0x38, 0xb0, 0x63, 0xfc, 0x54, 0xe3, 0x7f, 0x50,
	0xe7, 0x59, 0x1c, 0x96, 0x96, 0xd4, 0x0f, 0xbe, 0x01, 0xa4, 0xc2, 0xcf, 0x79, 0x14, 0x48, 0xe6,
	0x87, 0x69, 0x9e, 0xc8, 0xbe, 0x4e, 0x12, 0x8b, 0x98, 0x2d, 0x11, 0x6e, 0x81, 0xe3, 0x25, 0xb4,
	0xf7, 0x81, 0x90, 0x47, 0x71, 0xd4, 0x37, 0xc8, 0xce, 0xc0, 0x51, 0xdb, 0xe1, 0x94, 0xdb, 0xe1,
	0x6c, 0xca, 0xed, 0xf0, 0xcc, 0x42, 0xaf, 0x5a, 0x44, 0xf6, 0x0f, 0x0d, 0xda, 0xea, 0xf4, 0xff,
	0xb6, 0x02, 0x65, 0xca, 0xb5, 0x4a, 0xca, 0x67, 0x60, 0x16, 0x5f, 0xf1, 0xc4, 0x31, 0x10, 0xa4,
	0xbc, 0x8e, 0xa0, 0x79, 0x8c, 0x43, 0xf4, 0x8d, 0xa1, 0x3e, 0x32, 0x27, 0x6d, 0x15, 0x9b, 0x02,
	0xbd, 0x47, 0x76, 0x3c, 0x84, 0x76, 0x75, 0x28, 0x36, 0xa0, 0xb6, 0xfc, 0x68, 0x9d, 0x60, 0x13,
	0x8c, 0xeb, 0xe9, 0x7c, 0x61, 0x69, 0xe3, 0x97, 0xd0, 0x7a, 0xbc, 0x14, 0x3c, 0x05, 0x7d, 0xba,
	0x76, 0x15, 0x7f, 0x35, 0x5b, 0xbb, 0x96, 0x36, 0xbe, 0x01, 0xfc, 0x73, 0x6b, 0xb0, 0x05, 0xf5,
	0x95, 0x37, 0x77, 0x67, 0xd6, 0x09, 0xfe, 0x0f, 0xbd, 0xc5, 0x74, 0xbd, 0xf1, 0xe9, 0xdf, 0xdf,
	0xae, 0xae, 0xa6, 0x9b, 0x99, 0xa5, 0xe1, 0x33, 0xc0, 0x2a, 0xe2, 0xbb, 0xcb, 0xed, 0xcd, 0xc6,
	0xaa, 0x4d, 0x12, 0x30, 0x4b, 0x77, 0xd3, 0xd5, 0x1c, 0xdf, 0x41, 0x9d, 0x9e, 0x0e, 0xaa, 0x84,
	0xaa, 0x0f, 0x6d, 0x80, 0x55, 0x48, 0x1d, 0xc2, 0x3e, 0xc1, 0xb7, 0x60, 0x14, 0x41, 0xa3, 0x45,
	0x6c, 0x65, 0xe3, 0x06, 0xbd, 0x0a, 0x52, 0xca, 0x6f, 0x1b, 0x74, 0x73, 0xef, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xd5, 0x93, 0x7c, 0xe4, 0xfc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductsAPIClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsAPIClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type productsAPIClient struct {
	cc *grpc.ClientConn
}

func NewProductsAPIClient(cc *grpc.ClientConn) ProductsAPIClient {
	return &productsAPIClient{cc}
}

func (c *productsAPIClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/api.Products/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsAPIClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/api.Products/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsAPIServer is the server API for Products service.
type ProductsAPIServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

// UnimplementedProductsAPIServer can be embedded to have forward compatible implementations.
type UnimplementedProductsAPIServer struct {
}

func (*UnimplementedProductsAPIServer) Fetch(ctx context.Context, req *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (*UnimplementedProductsAPIServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterProductsAPIServer(s *grpc.Server, srv ProductsAPIServer) {
	s.RegisterService(&_ProductsAPI_serviceDesc, srv)
}

func _ProductsAPI_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsAPIServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Products/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsAPIServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Products/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsAPIServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductsAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Products",
	HandlerType: (*ProductsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _ProductsAPI_Fetch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProductsAPI_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products.proto",
}
